
analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_positional_boolean_parameters: ignore
    flutter_style_todos: ignore
    invalid_annotation_target: ignore
    only_throw_errors: ignore
    public_member_api_docs: ignore
    sort_constructors_first: ignore
    sort_unnamed_constructors_first: ignore
    
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_const_constructors: true
