name: tale_builder_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Shared
  myspace_design_system:
    path: /Users/shoh/Documents/github/personal/myspace/packages/myspace_design_system
  myspace_ui:
    path: /Users/shoh/Documents/github/personal/myspace/packages/myspace_ui
  myspace_core:
    path: /Users/shoh/Documents/github/personal/myspace/packages/myspace_core
    
  freezed_annotation: ^3.0.0
  supabase: ^2.6.3
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1
  collection: ^1.19.1
  flutter_tts: ^4.2.2
  file_picker: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4

flutter:
  uses-material-design: true
