name: myspace_data_mobile
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.8.3

  core_audio:
    path: ../core_audio

  # Freezed
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  myspace_data:
    path: /Users/shoh/Documents/github/personal/myspace/packages/myspace_data


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4

flutter: