name: mobile
description: "A new Flutter project."
homepage: www.shoh.dev
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # myspace
  myspace_data: 0.0.1
  myspace_design_system: 0.0.1

  # core
  simple_gesture_detector: ^0.2.1
  core_audio: 0.0.1
  # core_localization: 0.0.1
  # core_sensors: 0.0.1
  # core_assets: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true